#!/usr/bin/env bash

declare -A filtyper

filtyper[jpg]="image"
filtyper[jpeg]="image"
filtyper[png]="image"
filtyper[gif]="image"
filtyper[heic]="image"

filtyper[pdf]="pdf"

filtyper[doc]="word"
filtyper[docx]="word"
filtyper[pages]="word"


filtyper[xls]="tabell"
filtyper[xlsx]="tabell"
filtyper[csv]="tabell"
filtyper[numbers]="tabell"

filtyper[ppt]="presentation"
filtyper[pptx]="presentation"
filtyper[key]="presentation"

filtyper[mp3]="musik"
filtyper[wav]="musik"

filtyper[logicx]="musikprojekt"

filtyper[md]="text"
filtyper[txt]="text"
filtyper[rtf]="text"

filtyper[mp4]="video"
filtyper[mov]="video"

filtyper[zip]="paket"

# echo "${filtyper[*]}"
# echo "${!filtyper[*]}"



id_n_sort(){
	local fil="$1"
	local extension="${fil##*.}"
	extension="${extension,,}"
	local kategori="${filtyper[$extension]:-other}"
	mkdir -p "$HOME/Hämtningar/$kategori"
	mv "$fil" "$HOME/Hämtningar/$kategori"
}

inotifywait -m -e close_write -e moved_to --format '%w%f' ~/Hämtningar | 
	while read fil
	do id_n_sort "$fil"
	done
